name: Pull GHCR Image

# This workflow runs on any push to the main branch
on:
  workflow_dispatch:   # manually trigger

jobs:
  pull-image-job:
    # Use the standard GitHub-hosted runner
    runs-on: ubuntu-latest

    steps:
      # Step 1: Log in to the GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 2: Pull the specific Docker image
      - name: Pull Docker Image
        run: docker pull ghcr.io/javanderwal/scraperealestatecom:latest

      # Step 3: (Optional) Verify the image has been pulled
      - name: Verify Image
        run: docker images | grep scraperealestatecom

      # Step 4: Run the container and see the output
      - name: Run container
        run: docker run --rm -e SMTP_USER="${{ secrets.SMTP_USER }}" -e SMTP_PASSWORD="${{ secrets.SMTP_PASSWORD }}" -e EMAIL_TO="${{ secrets.EMAIL_TO }}" -e SCRAPFLY_API_KEY="${{ secrets.SCRAPFLY_API_KEY }}" ghcr.io/javanderwal/scraperealestatecom:latest
